check:
  - thoth-pytest-py38
  - thoth-precommit
  - overlays-build
overlays_dir: overlays
overlays:
  - name: download-dataset
    build:
      base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.20.1
      build-stratergy: Source
      registry: quay.io
      registry-org: harshad16
      registry-project: elyra-dataset
      registry-secret: thoth-station-thoth-pusher-secret

  - name: training
    build:
      base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.20.1
      build-stratergy: Source
      registry: quay.io
      registry-org: harshad16
      registry-project: elyra-training
      registry-secret: thoth-station-thoth-pusher-secret

  - name: inference
    build:
      base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.20.1
      build-stratergy: Source
      registry: quay.io
      registry-org: harshad16
      registry-project: elyra-inference
      registry-secret: thoth-station-thoth-pusher-secret
    deploy:
      project-org: "harshad16"
      project-name: "elyra-aidevsecops-tutorial"
      image-name: "elyra-aidevsecops-tutorial"
      overlay-contextpath: "manifests/overlays/test/imagestreamtag.yaml"
